trigger test

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -16,17 +16,17 @@ before_install:
   - export GALAXY_REPO=https://github.com/galaxyproject/galaxy
   - export GALAXY_RELEASE=release_16.04
   - export CONDA_PREFIX=$HOME/conda
+  #- export GALAXY_CONFIG_CONDA_DEBUG=True
+  #- travis_retry sudo apt-get install samtools
 
 install:
-  - pip install flake8
-  - pip install -q click==5.1
-  - pip install -q planemo
+  - pip install -q flake8 planemo
   - planemo conda_init --conda_prefix $CONDA_PREFIX
   - export PATH=$CONDA_PREFIX/bin:$PATH
-  - conda install -y -q conda=3.19.3
-  - conda create -y -q -c bioconda --name iuc_conda numpy==1.9.2 samtools=0.1.19 bcftools
+  - conda create -y -q -c bioconda --name iuc_conda samtools=0.1.19 bcftools
   - source activate iuc_conda
   - planemo --version
+  - conda --version
   - echo $TRAVIS_COMMIT_RANGE
   - planemo shed_lint --report_level warn --tools --fail_level error --recursive .
   - git diff --name-only $TRAVIS_COMMIT_RANGE | xargs -n1 dirname | ./filter_directories.py | sort -u > changed_repositories.list
@@ -46,9 +46,8 @@ script:
     then
       cat $CHUNK
       for DIR in `cat $CHUNK`; do planemo conda_install --conda_ensure_channels iuc,bioconda,r,bgruening --conda_prefix $CONDA_PREFIX $DIR ; done
-      for DIR in `cat $CHUNK`; do planemo test --conda_dependency_resolution --conda_prefix $CONDA_PREFIX --galaxy_branch $GALAXY_RELEASE  --galaxy_source $GALAXY_REPO --skip_venv $DIR || exit 1; done
+      for DIR in `cat $CHUNK`; do planemo test --conda_dependency_resolution --conda_prefix $CONDA_PREFIX --galaxy_branch $GALAXY_RELEASE  --galaxy_source $GALAXY_REPO $DIR || exit 1; done
     fi
-    
 
 after_success:
   - | 
