Update pr.yaml

diff --git a/.github/workflows/pr.yaml b/.github/workflows/pr.yaml
--- a/.github/workflows/pr.yaml
+++ b/.github/workflows/pr.yaml
@@ -2,7 +2,8 @@ name: Galaxy Tool Linting and Tests for push and PR
 on: [push, pull_request]
 env:
   GALAXY_REPO: https://github.com/galaxyproject/galaxy
-  GALAXY_RELEASE: release_20.05
+  GALAXY_RELEASE: release_20.09
+  MAX_CHUNKS: 4
 jobs:
   # the setup job does two things:
   # 1. cache the pip cache and .planemo
@@ -14,6 +15,11 @@ jobs:
   setup:
     name: Setup cache and determine changed repositories
     runs-on: ubuntu-latest
+    outputs:
+      galaxy_head_sha: ${{ steps.get-galaxy-sha.outputs.galaxy_head_sha }}
+      commit_range: ${{ steps.get-commit-range.outputs.commit_range }}
+      nchunks: ${{ steps.get-chunks.outputs.nchunks }}
+      chunk_list: ${{ steps.get-chunks.outputs.chunk_list }}
     strategy:
       matrix:
         python-version: [3.7]
@@ -27,29 +33,24 @@ jobs:
         echo 'base_ref: ${{ github.base_ref }}'
         echo 'event.before: ${{ github.event.before }}'
         echo 'event.after: ${{ github.event.after }}'
-    - uses: actions/setup-python@v2
+    - uses: actions/setup-python@v1
       with:
         python-version: ${{ matrix.python-version }}
-    - name: Determine latest galaxy commit
-      run: echo ::set-env name=GALAXY_HEAD_SHA::$(git ls-remote ${{ env.GALAXY_REPO }} refs/heads/${{ env.GALAXY_RELEASE }} | cut -f1)
-    - name: Save latest galaxy commit to artifact file
-      run: echo ${{ env.GALAXY_HEAD_SHA }} > galaxy.sha
-    - uses: actions/upload-artifact@v2
-      with:
-        name: Workflow artifacts
-        path: galaxy.sha
+    - name: Determine latest commit in the Galaxy repo
+      id: get-galaxy-sha
+      run: echo "::set-output name=galaxy_head_sha::$(git ls-remote ${{ env.GALAXY_REPO }} refs/heads/${{ env.GALAXY_RELEASE }} | cut -f1)"
     - name: Cache .cache/pip
       uses: actions/cache@v2
       id: cache-pip
       with:
         path: ~/.cache/pip
-        key: pip_cache_py_${{ matrix.python-version }}_gxy_${{ env.GALAXY_HEAD_SHA }}
+        key: pip_cache_py_${{ matrix.python-version }}_gxy_${{ steps.get-galaxy-sha.outputs.galaxy_head_sha }}
     - name: Cache .planemo
       uses: actions/cache@v2
       id: cache-planemo
       with:
         path: ~/.planemo
-        key: planemo_cache_py_${{ matrix.python-version }}_gxy_${{ env.GALAXY_HEAD_SHA }}
+        key: planemo_cache_py_${{ matrix.python-version }}_gxy_${{ steps.get-galaxy-sha.outputs.galaxy_head_sha }}
     # Install the `wheel` package so that when installing other packages which
     # are not available as wheels, pip will build a wheel for them, which can be cached.
     - name: Install wheel
@@ -75,21 +76,51 @@ jobs:
       if: github.ref != 'refs/heads/master' && github.event_name == 'push'
       run: |
         git fetch origin master
-        echo ::set-env name=COMMIT_RANGE::"origin/master..."
+        echo "COMMIT_RANGE=origin/master..." >> $GITHUB_ENV
     - name: Set commit range (push to the master branch, e.g. merge)
       if: github.ref == 'refs/heads/master' && github.event_name == 'push'
-      run: echo ::set-env name=COMMIT_RANGE::${{ github.event.before }}..""
+      run: echo "COMMIT_RANGE=${{ github.event.before }}.." >> $GITHUB_ENV
     - name: Set commit range (pull request)
       if: github.event_name == 'pull_request'
-      run: echo ::set-env name=COMMIT_RANGE::"HEAD~.."
+      run: echo "COMMIT_RANGE=HEAD~.." >> $GITHUB_ENV
+    - id: get-commit-range
+      run: echo "::set-output name=commit_range::$COMMIT_RANGE"
     - name: Planemo ci_find_repos
-      run: planemo ci_find_repos --changed_in_commit_range ${{ env.COMMIT_RANGE }} --exclude packages --exclude deprecated --exclude_from .tt_skip --output changed_repositories.list
+      run: planemo ci_find_repos --changed_in_commit_range $COMMIT_RANGE --exclude packages --exclude deprecated --exclude_from .tt_skip --output changed_repositories.list
     - name: Show repo list
       run: cat changed_repositories.list
-    - uses: actions/upload-artifact@v2.0.1
+    - uses: actions/upload-artifact@v2
       with:
         name: Workflow artifacts
         path: changed_repositories.list
+    - name: install condor
+      run: sudo apt-get install htcondor -y
+    - name: 'configure htcondor'
+      run: echo 'TRUST_UID_DOMAIN = true'| sudo tee -a  /etc/condor/condor_config
+    - name: start htcondor
+      run: sudo systemctl start condor
+    - name: Planemo ci_find_tools for the changed repos
+      run: |
+        touch changed_tools.list
+        if [ -s changed_repositories.list ]; then
+            planemo ci_find_tools --output changed_tools.list $(cat changed_repositories.list)
+        fi
+    - name: Show tool list
+      run: cat changed_tools.list
+    - name: Compute chunks
+      id: get-chunks
+      run: |
+        nchunks=$(wc -l < changed_tools.list)
+        if [ "$nchunks" -gt "$MAX_CHUNKS" ]; then
+            nchunks=$MAX_CHUNKS
+        elif [ "$nchunks" -eq 0 ]; then
+            nchunks=1
+        fi
+        echo "::set-output name=nchunks::$nchunks"
+        echo "::set-output name=chunk_list::[$(seq -s ", " 0 $(($nchunks - 1)))]"
+    - name: Show chunks
+      run: |
+        echo 'Using ${{ steps.get-chunks.outputs.nchunks }} chunks (${{ steps.get-chunks.outputs.chunk_list }})'
 
   # Planemo lint the changed repositories
   lint:
@@ -105,22 +136,20 @@ jobs:
     # and use it as the current working directory
     - uses: actions/checkout@v2
       with:
-        fetch-depth: 1
-    - uses: actions/setup-python@v2
+        fetch-depth: 0
+    - uses: actions/setup-python@v1
       with:
         python-version: ${{ matrix.python-version }}
     - uses: actions/download-artifact@v2
       with:
         name: Workflow artifacts
         path: ../workflow_artifacts/
-    - name: Determine latest galaxy commit
-      run: echo ::set-env name=GALAXY_HEAD_SHA::$(cat ../workflow_artifacts/galaxy.sha)
     - name: Cache .cache/pip
       uses: actions/cache@v2
       id: cache-pip
       with:
         path: ~/.cache/pip
-        key: pip_cache_py_${{ matrix.python-version }}_gxy_${{ env.GALAXY_HEAD_SHA }}
+        key: pip_cache_py_${{ matrix.python-version }}_gxy_${{ needs.setup.outputs.galaxy_head_sha }}
     - name: Install Planemo
       run: pip install planemo
     - name: Planemo lint
@@ -129,6 +158,18 @@ jobs:
         while read -r DIR; do
             planemo shed_lint --tools --ensure_metadata --urls --report_level warn --fail_level error --recursive "$DIR";
         done < ../workflow_artifacts/changed_repositories.list
+    - name: Planemo ci_find_tools for the commit range
+      run: planemo ci_find_tools --changed_in_commit_range ${{ needs.setup.outputs.commit_range }} --exclude packages --exclude deprecated --exclude_from .tt_skip --output changed_tools.list
+    - name: Check if each changed tool is in the list of changed repositories
+      run: |
+        set -e
+        while read -r TOOL; do
+            # Check if any changed repo dir is a substring of $TOOL
+            if ! echo $TOOL | grep -qf ../workflow_artifacts/changed_repositories.list; then
+                echo "Tool $TOOL not in changed repositories list: .shed.yml file missing" >&2
+                exit 1
+            fi
+        done < changed_tools.list
 
   # flake8 of Python scripts in the changed repositories
   flake8:
@@ -145,21 +186,19 @@ jobs:
     - uses: actions/checkout@v2
       with:
         fetch-depth: 1
-    - uses: actions/setup-python@v2
+    - uses: actions/setup-python@v1
       with:
         python-version: ${{ matrix.python-version }}
     - uses: actions/download-artifact@v2
       with:
         name: Workflow artifacts
         path: ../workflow_artifacts/
-    - name: Determine latest galaxy commit
-      run: echo ::set-env name=GALAXY_HEAD_SHA::$(cat ../workflow_artifacts/galaxy.sha)
     - name: Cache .cache/pip
       uses: actions/cache@v2
       id: cache-pip
       with:
         path: ~/.cache/pip
-        key: pip_cache_py_${{ matrix.python-version }}_gxy_${{ env.GALAXY_HEAD_SHA }}
+        key: pip_cache_py_${{ matrix.python-version }}_gxy_${{ needs.setup.outputs.galaxy_head_sha }}
     - name: Install flake8
       run: pip install flake8 flake8-import-order
     - name: Flake8
@@ -203,7 +242,7 @@ jobs:
     - name: lintr
       run: |
         library(lintr)
-        linters <- with_defaults(line_length_linter = NULL)
+        linters <- with_defaults(line_length_linter = NULL, object_usage_linter = NULL)
         con <- file("../workflow_artifacts/changed_repositories.list", "r")
         status <- 0
         while (TRUE) {
@@ -233,7 +272,7 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        chunk: [0, 1, 2, 3]
+        chunk: ${{ fromJson(needs.setup.outputs.chunk_list) }}
         python-version: [3.7]
     services:
       postgres:
@@ -250,85 +289,61 @@ jobs:
     - uses: actions/checkout@v2
       with:
         fetch-depth: 1
-    #- name: Setup tmate session
-    #  uses: mxschmitt/action-tmate@v3
-    - uses: actions/setup-python@v2
+    - uses: actions/setup-python@v1
       with:
         python-version: ${{ matrix.python-version }}
     - uses: actions/download-artifact@v2
       with:
         name: Workflow artifacts
         path: ../workflow_artifacts/
-    - name: Determine latest galaxy commit
-      run: echo ::set-env name=GALAXY_HEAD_SHA::$(cat ../workflow_artifacts/galaxy.sha)
     - name: Cache .cache/pip
       uses: actions/cache@v2
       id: cache-pip
       with:
         path: ~/.cache/pip
-        key: pip_cache_py_${{ matrix.python-version }}_gxy_${{ env.GALAXY_HEAD_SHA }}
+        key: pip_cache_py_${{ matrix.python-version }}_gxy_${{ needs.setup.outputs.galaxy_head_sha }}
     - name: Cache .planemo
       uses: actions/cache@v2
       id: cache-planemo
       with:
         path: ~/.planemo
-        key: planemo_cache_py_${{ matrix.python-version }}_gxy_${{ env.GALAXY_HEAD_SHA }}
+        key: planemo_cache_py_${{ matrix.python-version }}_gxy_${{ needs.setup.outputs.galaxy_head_sha }}
     - name: Install Planemo
       run: pip install planemo
-    - name: install condor
-      run: sudo apt-get install htcondor -y
-    - name: 'configure htcondor'
-      run: echo 'TRUST_UID_DOMAIN = true'| sudo tee -a  /etc/condor/condor_config
-    - name: start htcondor
-      run: sudo systemctl start condor
-    - name: Planemo ci_find_tools
+    - name: Planemo ci_find_tools for the change repos, chunked
       run: |
-        touch changed_repositories_chunk.list changed_tools_chunk.list
+        touch changed_tools_chunk.list
         if [ -s ../workflow_artifacts/changed_repositories.list ]; then
-            if [ $(wc -l < ../workflow_artifacts/changed_repositories.list) -eq 1 ]; then
-                planemo ci_find_tools --chunk_count 4 --chunk ${{ matrix.chunk }} \
-                               --output changed_tools_chunk.list \
-                               $(cat ../workflow_artifacts/changed_repositories.list)
-            else
-                planemo ci_find_repos --chunk_count 4 --chunk ${{ matrix.chunk }} \
-                               --output changed_repositories_chunk.list \
-                               $(cat ../workflow_artifacts/changed_repositories.list)
-            fi
+          planemo ci_find_tools --chunk_count ${{ needs.setup.outputs.nchunks }} --chunk ${{ matrix.chunk }} --group_tools --output changed_tools_chunk.list $(cat ../workflow_artifacts/changed_repositories.list)
         fi
-    - name: Show changed tools/repositories chunk list
-      run: cat changed_tools_chunk.list changed_repositories_chunk.list
+    - name: Show changed tools chunk list
+      run: cat changed_tools_chunk.list
     - name: Planemo test tools
       run: |
-        if grep -lqf .tt_biocontainer_skip changed_tools_chunk.list changed_repositories_chunk.list; then
+        mkdir json_output
+        while read -r TOOL_GROUP; do
+            # Check if any of the lines in .tt_biocontainer_skip is a substring of $TOOL_GROUP
+            if echo $TOOL_GROUP | grep -qf .tt_biocontainer_skip; then
                 PLANEMO_OPTIONS="--job_config_file job_conf.xml_condor"
-        else
+            else
                 PLANEMO_OPTIONS="--biocontainers --no_dependency_resolution --no_conda_auto_init --job_config_file job_conf.xml_condor"
-        fi
-        if [ -s changed_tools_chunk.list ]; then
-            PIP_QUIET=1 planemo test --database_connection postgresql://postgres:postgres@localhost:5432/galaxy $PLANEMO_OPTIONS --galaxy_source $GALAXY_REPO --galaxy_branch $GALAXY_RELEASE --galaxy_python_version ${{ matrix.python-version }} --test_output_json tool_test_output.json $(cat changed_tools_chunk.list) || true
+            fi
+            json=$(mktemp -u -p json_output --suff .json)
+            PIP_QUIET=1 planemo test --database_connection postgresql://postgres:postgres@localhost:5432/galaxy $PLANEMO_OPTIONS --galaxy_source $GALAXY_REPO --galaxy_branch $GALAXY_RELEASE --galaxy_python_version ${{ matrix.python-version }} --test_output_json "$json" $TOOL_GROUP || true
             docker system prune --all --force --volumes || true
-        elif [ -s changed_repositories_chunk.list ]; then
-            while read -r DIR; do
-                if [[ "$DIR" =~ ^data_managers.* ]]; then
-                    TESTPATH=$(planemo ci_find_tools "$DIR")
-                else
-                    TESTPATH="$DIR"
-                fi
-                PIP_QUIET=1 planemo test --database_connection postgresql://postgres:postgres@localhost:5432/galaxy $PLANEMO_OPTIONS --galaxy_source $GALAXY_REPO --galaxy_branch $GALAXY_RELEASE --galaxy_python_version ${{ matrix.python-version }} --test_output_json "$DIR"/tool_test_output.json "$TESTPATH" || true
-                docker system prune --all --force --volumes || true
-            done < changed_repositories_chunk.list
-        else
-            echo '{"tests":[]}' > tool_test_output.json
+        done < changed_tools_chunk.list
+        if [ ! -s changed_tools_chunk.list ]; then
+            echo '{"tests":[]}' > "$(mktemp -u -p json_output --suff .json)"
         fi
     - name: Merge tool_test_output.json files
-      run: find . -name tool_test_output.json -exec sh -c 'planemo merge_test_reports "$@" tool_test_output.json' sh {} +
+      run: planemo merge_test_reports json_output/*.json tool_test_output.json
     - name: Create tool_test_output.html
       run: planemo test_reports tool_test_output.json --test_output tool_test_output.html
     - name: Copy artifacts into place
       run: |
         mkdir upload
         mv tool_test_output.json tool_test_output.html upload/
-    - uses: actions/upload-artifact@v2.0.1
+    - uses: actions/upload-artifact@v2
       with:
         name: 'Tool test output ${{ matrix.chunk  }}'
         path: upload
@@ -340,7 +355,7 @@ jobs:
   #   and fail this step if this is the case
   combine_outputs:
     name: Combine chunked test results
-    needs: test
+    needs: [setup, test]
     strategy:
       matrix:
         python-version: [3.7]
@@ -350,17 +365,15 @@ jobs:
     - uses: actions/download-artifact@v2
       with:
         path: artifacts
-    - uses: actions/setup-python@v2
+    - uses: actions/setup-python@v1
       with:
         python-version: ${{ matrix.python-version }}
-    - name: Determine latest galaxy commit
-      run: echo ::set-env name=GALAXY_HEAD_SHA::$(cat "artifacts/Workflow artifacts/galaxy.sha")
     - name: Cache .cache/pip
       uses: actions/cache@v2
       id: cache-pip
       with:
         path: ~/.cache/pip
-        key: pip_cache_py_${{ matrix.python-version }}_gxy_${{ env.GALAXY_HEAD_SHA }}
+        key: pip_cache_py_${{ matrix.python-version }}_gxy_${{ needs.setup.outputs.galaxy_head_sha }}
     - name: Install Planemo
       run: pip install planemo
     - name: Install jq
@@ -373,11 +386,11 @@ jobs:
       run: |
         mkdir upload
         mv tool_test_output.json tool_test_output.html upload/
-    - uses: actions/upload-artifact@v2.0.1
+    - uses: actions/upload-artifact@v2
       with:
         name: 'All tool test results'
         path: upload
-    - name: Check status of combined status
+    - name: Check status of combined outputs
       run: |
         if jq '.["tests"][]["data"]["status"]' upload/tool_test_output.json | grep -v "success"; then
             echo "Unsuccessful tests found, inspect the 'All tool test results' artifact for details."
@@ -387,12 +400,12 @@ jobs:
   # deploy the tools to the toolsheds (first TTS for testing)
   deploy:
     name: Deploy
-    needs: [lint,flake8,lintr,combine_outputs]
+    needs: [setup, lint, flake8, lintr, combine_outputs]
     strategy:
       matrix:
         python-version: [3.7]
     runs-on: ubuntu-latest
-    if: github.ref == 'refs/heads/master'
+    if: github.ref == 'refs/heads/master' && github.repository_owner == 'bgruening'
     steps:
     - uses: actions/checkout@v2
       with:
@@ -404,19 +417,17 @@ jobs:
       with:
         name: Workflow artifacts
         path: ../workflow_artifacts/
-    - name: Determine latest galaxy commit
-      run: echo ::set-env name=GALAXY_HEAD_SHA::$(cat ../workflow_artifacts/galaxy.sha)
     - name: Cache .cache/pip
       uses: actions/cache@v2
       id: cache-pip
       with:
         path: ~/.cache/pip
-        key: pip_cache_py_${{ matrix.python-version }}_gxy_${{ env.GALAXY_HEAD_SHA }}
+        key: pip_cache_py_${{ matrix.python-version }}_gxy_${{ needs.setup.outputs.galaxy_head_sha }}
     - name: Install Planemo
       run: pip install planemo
     - name: Deploy on testtoolshed
       env:
-        SHED_KEY: ${{ secrets.tts_api_key }}
+        SHED_KEY: ${{ secrets.TTS_API_KEY }}
       run: |
         while read -r DIR; do
             planemo shed_update --shed_target testtoolshed --shed_key "${{ env.SHED_KEY }}" --force_repository_creation "$DIR" || exit 1;
@@ -424,9 +435,8 @@ jobs:
       continue-on-error: true
     - name: Deploy on toolshed
       env:
-        SHED_KEY: ${{ secrets.ts_api_key }}
+        SHED_KEY: ${{ secrets.TS_API_KEY }}
       run: |
         while read -r DIR; do
             planemo shed_update --shed_target toolshed --shed_key "${{ env.SHED_KEY }}" --force_repository_creation "$DIR" || exit 1;
         done < ../workflow_artifacts/changed_repositories.list
-
